-- 결과보고(AS_RESULT) 기능 테스트를 위해 필요한 테이블/더미데이터
-- ENGINEER, AS_REQUEST는 현재 DB에 ENGINEER_NO/REQUEST_NO가 AUTO_INCREMENT가 아니라서
-- 번호를 직접 지정해서 넣습니다. (기존 테이블 구조는 건드리지 않음)

-- ENGINEER, AS_REQUEST 더미데이터가 비어있어서 채워줍니다 (member.kimgisa는 이미 있음)
INSERT INTO ENGINEER (ENGINEER_NO, MEM_NO, ENGINEER_NAME, ENGINEER_TEL, SPECIALTY)
SELECT 1, MEM_NO, '김기사', '010-1111-2222', '에어컨'
FROM MEMBER WHERE MEM_ID = 'kimgisa'
AND NOT EXISTS (SELECT 1 FROM ENGINEER WHERE ENGINEER_NO = 1);

INSERT INTO AS_REQUEST (REQUEST_NO, CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM)
SELECT 1, '강남구 고객님', '010-3333-4444', '서울시 강남구', '에어컨', '에어컨 작동 불량'
WHERE NOT EXISTS (SELECT 1 FROM AS_REQUEST WHERE REQUEST_NO = 1);

-- 박성인 파트: AS_SCHEDULE, AS_RESULT는 기존 테이블생성쿼리.sql에 없어서 신규 생성
CREATE TABLE IF NOT EXISTS AS_SCHEDULE (
    SCHEDULE_NO INT AUTO_INCREMENT PRIMARY KEY,
    REQUEST_NO INT NOT NULL,
    ENGINEER_NO INT NOT NULL,
    START_TIME DATETIME NULL,
    END_TIME DATETIME NULL,
    FOREIGN KEY (REQUEST_NO) REFERENCES AS_REQUEST(REQUEST_NO),
    FOREIGN KEY (ENGINEER_NO) REFERENCES ENGINEER(ENGINEER_NO)
);

CREATE TABLE IF NOT EXISTS AS_RESULT (
    RESULT_NO INT AUTO_INCREMENT PRIMARY KEY,
    SCHEDULE_NO INT NOT NULL,
    PROCESS_DATE DATETIME NOT NULL,
    PROCESS_CONTENT VARCHAR(500) NOT NULL,
    RESULT_STATUS VARCHAR(20) NOT NULL DEFAULT '완료',
    IMAGE_PATH VARCHAR(200),
    IMAGE_PATH2 VARCHAR(200),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SCHEDULE_NO) REFERENCES AS_SCHEDULE(SCHEDULE_NO)
);

-- 처리사진을 2장까지 받을 수 있도록 컬럼 추가 (이미 AS_RESULT가 만들어져 있는 경우 대비)
ALTER TABLE AS_RESULT ADD COLUMN IF NOT EXISTS IMAGE_PATH2 VARCHAR(200) AFTER IMAGE_PATH;

-- 오늘(실행일) 일정으로 김기사에게 배정
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
SELECT 1, 1, CONCAT(CURDATE(), ' 09:00:00'), CONCAT(CURDATE(), ' 12:00:00')
WHERE NOT EXISTS (SELECT 1 FROM AS_SCHEDULE WHERE REQUEST_NO = 1 AND ENGINEER_NO = 1);

-- 대시보드 화면 테스트용 더미데이터 (진행예정/진행중/완료 세 가지 상태를 한 번에 볼 수 있게)
INSERT INTO AS_REQUEST (REQUEST_NO, CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM)
SELECT 2, '서초구 고객님', '010-2222-3333', '서울시 서초구', '보일러', '온수가 나오지 않음'
WHERE NOT EXISTS (SELECT 1 FROM AS_REQUEST WHERE REQUEST_NO = 2);

INSERT INTO AS_REQUEST (REQUEST_NO, CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM)
SELECT 3, '마포구 고객님', '010-4444-5555', '서울시 마포구', '냉난방기', '소음이 심하게 남'
WHERE NOT EXISTS (SELECT 1 FROM AS_REQUEST WHERE REQUEST_NO = 3);

INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
SELECT 2, 1, CONCAT(CURDATE(), ' 13:00:00'), CONCAT(CURDATE(), ' 15:00:00')
WHERE NOT EXISTS (SELECT 1 FROM AS_SCHEDULE WHERE REQUEST_NO = 2 AND ENGINEER_NO = 1);

INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
SELECT 3, 1, CONCAT(CURDATE(), ' 15:30:00'), CONCAT(CURDATE(), ' 17:00:00')
WHERE NOT EXISTS (SELECT 1 FROM AS_SCHEDULE WHERE REQUEST_NO = 3 AND ENGINEER_NO = 1);

-- REQUEST_NO 1은 완료, 2는 아직 접수 상태(진행예정), 3은 진행중 상태로 맞춰서
-- 대시보드에서 세 가지 카드(진행예정 버튼 / 진행중 뱃지 / 완료 뱃지)를 한 번에 볼 수 있게 함
UPDATE AS_REQUEST SET STATUS = 'IN_PROGRESS' WHERE REQUEST_NO = 3;
