-- 대시보드(오늘의 일정 + 이번 달 달력) 확인용 추가 더미데이터
-- 대상 기사: kimgisa(김기사, ENGINEER_NO=1)
-- 오늘(실행일 기준) 2건 + 이번 달 다른 날짜 3건 + 다음 달 1건(달력 월 이동 확인용)
-- REQUEST_NO는 AUTO_INCREMENT라 번호를 지정하지 않고, 방금 넣은 REQUEST의 번호를
-- @request_no 세션변수로 받아서 바로 AS_SCHEDULE에 사용합니다.

-- 1) 오늘 09:00~11:00 (진행예정 버튼 확인용 -> RECEIVED)
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('동구 고객님', '010-1111-2222', '대전광역시 동구 계룡로 123', '에어컨', '실외기 소음', 'RECEIVED');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, CONCAT(CURDATE(), ' 09:00:00'), CONCAT(CURDATE(), ' 11:00:00'));

-- 2) 오늘 14:00~15:00 (진행중 뱃지 확인용 -> IN_PROGRESS)
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('유성구 고객님', '010-2222-3333', '대전광역시 유성구 대학로 99', '보일러', '온수가 미지근함', 'IN_PROGRESS');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, CONCAT(CURDATE(), ' 14:00:00'), CONCAT(CURDATE(), ' 15:00:00'));

-- 3) 이번 달 16일 10:00~12:00
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('중구 고객님', '010-3333-4444', '대전광역시 중구 대흥동 45', '냉난방기', '필터 청소 요청', 'ASSIGNED');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, DATE_FORMAT(CURDATE(), '%Y-%m-16 10:00:00'), DATE_FORMAT(CURDATE(), '%Y-%m-16 12:00:00'));

-- 4) 이번 달 20일 13:00~14:30
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('서구 고객님', '010-4444-5555', '대전광역시 서구 둔산동 78', '에어컨', '리모컨 고장', 'ASSIGNED');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, DATE_FORMAT(CURDATE(), '%Y-%m-20 13:00:00'), DATE_FORMAT(CURDATE(), '%Y-%m-20 14:30:00'));

-- 5) 이번 달 25일 09:30~11:00
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('대덕구 고객님', '010-5555-6666', '대전광역시 대덕구 오정동 12', '보일러', '누수 의심', 'ASSIGNED');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, DATE_FORMAT(CURDATE(), '%Y-%m-25 09:30:00'), DATE_FORMAT(CURDATE(), '%Y-%m-25 11:00:00'));

-- 6) 다음 달 3일 10:00~12:00 (달력 "다음 달" 이동 확인용)
INSERT INTO REQUEST (CUSTOMER_NAME, CUSTOMER_TEL, CUSTOMER_ADDR, PRODUCT_TYPE, SYMPTOM, STATUS)
VALUES ('강남구 고객님', '010-6666-7777', '서울특별시 강남구 테헤란로 45', '에어컨', '신규 설치 문의', 'ASSIGNED');
SET @request_no = LAST_INSERT_ID();
INSERT INTO AS_SCHEDULE (REQUEST_NO, ENGINEER_NO, START_TIME, END_TIME)
VALUES (@request_no, 1, DATE_FORMAT(CURDATE() + INTERVAL 1 MONTH, '%Y-%m-03 10:00:00'), DATE_FORMAT(CURDATE() + INTERVAL 1 MONTH, '%Y-%m-03 12:00:00'));

COMMIT;
