-- 만족도 조사를 단일 별점 1개에서 3개 항목(방문/시간준수, 친절도/응대, A/S 처리결과)으로 확장
-- 기존 SCORE 컬럼 값은 SCORE_VISIT으로 이름만 바뀌고, 새로 생기는 두 컬럼은 기존 값과 동일하게 채워서
-- (기존 174건 더미데이터의 "3개 항목 평균" == 예전 단일 점수와 똑같이 유지됨. 즉 기존 그래프/비교 수치가 안 깨짐)
-- 실제로 새로 들어오는 설문 제출부터는 진짜 3개 항목 각각 값이 저장됩니다.

ALTER TABLE SATISFACTION CHANGE COLUMN SCORE SCORE_VISIT TINYINT NOT NULL COMMENT '기사 방문 및 시간 준수 만족도 (1~5)';
ALTER TABLE SATISFACTION ADD COLUMN SCORE_KINDNESS TINYINT NULL COMMENT '기사의 친절도 및 응대 만족도 (1~5)' AFTER SCORE_VISIT;
ALTER TABLE SATISFACTION ADD COLUMN SCORE_RESULT TINYINT NULL COMMENT 'A/S 처리 결과에 대한 전반적인 만족도 (1~5)' AFTER SCORE_KINDNESS;

UPDATE SATISFACTION
SET SCORE_KINDNESS = SCORE_VISIT, SCORE_RESULT = SCORE_VISIT
WHERE SCORE_KINDNESS IS NULL;

ALTER TABLE SATISFACTION MODIFY COLUMN SCORE_KINDNESS TINYINT NOT NULL COMMENT '기사의 친절도 및 응대 만족도 (1~5)';
ALTER TABLE SATISFACTION MODIFY COLUMN SCORE_RESULT TINYINT NOT NULL COMMENT 'A/S 처리 결과에 대한 전반적인 만족도 (1~5)';

COMMIT;
