-- ERDCloud 등에 SQL Import로 붙여넣어 ERD를 그려볼 수 있도록 정리한 버전입니다.
-- 원본 대비 바뀐 점은 채팅 답변에 따로 정리해뒀습니다. (구조/데이터는 바꾸지 않았습니다)

-- 1. MEMBER (독립)
CREATE TABLE MEMBER (
    MEM_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '회원 고유번호 (PK)',
    MEM_ID VARCHAR(30) NOT NULL UNIQUE COMMENT '로그인 아이디',
    MEM_PW VARCHAR(100) NOT NULL COMMENT '비밀번호',
    MEM_NAME VARCHAR(30) NOT NULL COMMENT '이름',
    ROLE ENUM('admin', 'repairman', 'user') NOT NULL DEFAULT 'user' COMMENT '권한 (관리자/기사/일반회원)'
);

-- 2. ENGINEER (MEMBER 참조)
CREATE TABLE ENGINEER (
    ENGINEER_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '기사 고유번호 (PK)',
    MEM_NO INT NOT NULL COMMENT '회원번호 (MEMBER FK)',
    ENGINEER_NAME VARCHAR(30) NOT NULL COMMENT '기사 이름',
    ENGINEER_TEL VARCHAR(20) NOT NULL COMMENT '연락처',
    SPECIALTY VARCHAR(50) COMMENT '전문 분야',
    WORK_START_TIME TIME COMMENT '근무 시작 시간',
    WORK_END_TIME TIME COMMENT '근무 종료 시간',
    STATUS VARCHAR(20) DEFAULT 'WORK' COMMENT '근무 상태 (WORK/REST)',
    CONSTRAINT FK_ENGINEER_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER (MEM_NO)
);

-- 3. REQUEST (MEMBER 참조)
CREATE TABLE REQUEST (
    REQUEST_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT 'AS 요청 고유번호 (PK)',
    MEM_NO INT NOT NULL COMMENT '요청 회원번호 (MEMBER FK)',
    CUSTOMER_NAME VARCHAR(30) NOT NULL COMMENT '고객명',
    CUSTOMER_TEL VARCHAR(20) NOT NULL COMMENT '고객 연락처',
    CUSTOMER_ADDR VARCHAR(100) NOT NULL COMMENT '고객 주소',
    PRODUCT_TYPE VARCHAR(30) COMMENT '제품 종류',
    SYMPTOM VARCHAR(200) COMMENT '증상/요청 내용',
    REQUEST_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '접수일시',
    WISH_DATE DATETIME COMMENT '희망 방문일',
    STATUS VARCHAR(20) DEFAULT 'RECEIVED' COMMENT '상태 (RECEIVED/ASSIGNED/IN_PROGRESS/COMPLETED/CANCELED)',
    CONSTRAINT FK_REQUEST_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER (MEM_NO)
);

-- 4. AS_SCHEDULE (REQUEST, ENGINEER 참조)
CREATE TABLE AS_SCHEDULE (
    SCHEDULE_NO INT AUTO_INCREMENT COMMENT '일정 고유번호 (PK)',
    REQUEST_NO INT NOT NULL COMMENT 'AS 요청번호 (REQUEST FK)',
    ENGINEER_NO INT NOT NULL COMMENT '배정 기사번호 (ENGINEER FK)',
    FIX_DATE DATE NOT NULL COMMENT '확정 방문일',
    START_TIME DATETIME NOT NULL COMMENT '방문 시작 시간',
    END_TIME DATETIME NOT NULL COMMENT '방문 종료 시간',
    STATUS VARCHAR(20) DEFAULT 'ASSIGNED' COMMENT '일정 상태',
    CONSTRAINT PK_SCHEDULE PRIMARY KEY (SCHEDULE_NO),
    CONSTRAINT FK_SCHEDULE_REQUEST FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO),
    CONSTRAINT FK_SCHEDULE_ENGINEER FOREIGN KEY (ENGINEER_NO) REFERENCES ENGINEER (ENGINEER_NO)
);

-- 5. AS_RESULT (AS_SCHEDULE 참조)
CREATE TABLE AS_RESULT (
    RESULT_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '결과보고 고유번호 (PK)',
    SCHEDULE_NO INT NOT NULL COMMENT '일정번호 (AS_SCHEDULE FK)',
    PROCESS_DATE DATETIME NOT NULL COMMENT '처리 일시',
    PROCESS_CONTENT VARCHAR(500) NOT NULL COMMENT '처리 내용',
    RESULT_STATUS VARCHAR(20) NOT NULL DEFAULT '완료' COMMENT '처리 상태',
    IMAGE_PATH VARCHAR(200) COMMENT '첨부 사진 경로 1',
    IMAGE_PATH2 VARCHAR(200) COMMENT '첨부 사진 경로 2',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    CONSTRAINT FK_RESULT_SCHEDULE FOREIGN KEY (SCHEDULE_NO) REFERENCES AS_SCHEDULE (SCHEDULE_NO)
);

-- 6. SATISFACTION (AS_SCHEDULE, ENGINEER 참조)
CREATE TABLE SATISFACTION (
    SURVEY_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '만족도 조사 고유번호 (PK)',
    SCHEDULE_NO INT NULL COMMENT '대상 일정번호 (AS_SCHEDULE FK)',
    ENGINEER_NO INT NOT NULL COMMENT '평가 대상 기사번호 (ENGINEER FK)',
    SCORE_VISIT TINYINT NOT NULL COMMENT '기사 방문 및 시간 준수 만족도 (1~5)',
    SCORE_KINDNESS TINYINT NOT NULL COMMENT '기사의 친절도 및 응대 만족도 (1~5)',
    SCORE_RESULT TINYINT NOT NULL COMMENT 'A/S 처리 결과에 대한 전반적인 만족도 (1~5)',
    COMMENT_TEXT VARCHAR(300) NULL COMMENT '자유 의견',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일시',
    CONSTRAINT FK_SATISFACTION_SCHEDULE FOREIGN KEY (SCHEDULE_NO) REFERENCES AS_SCHEDULE (SCHEDULE_NO),
    CONSTRAINT FK_SATISFACTION_ENGINEER FOREIGN KEY (ENGINEER_NO) REFERENCES ENGINEER (ENGINEER_NO)
);
